services:
  web:
    container_name: web
    build:
      context: ./web
    ports:
      - "$WEB_PORT:80"
    environment:
      - SERVER_URL=http://server
    restart: unless-stopped

  server:
    container_name: server
    build:
      context: ./server
    ports:
      - "$SERVER_PORT:80"
    # environment:
    #   - LOKI_URL=http://loki
    restart: unless-stopped

  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "$LOKI_PORT:3100"
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "$GRAFANA_PORT:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  e2e:
    profiles:
      - e2e
    container_name: e2e
    build:
      context: ./e2e
    environment:
      - WEB_URL=http://web
    depends_on:
      web:
        condition: service_healthy
      server:
        condition: service_healthy
    volumes:
      - ./playwright-report:/app/playwright-report

volumes:
  grafana-data:
