name: ci

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: start services
        run: docker compose up --build --detach

      - name: stop services
        if: always()
        run: docker compose down
